#!/bin/bash

set -ex

if ( echo $CIP_ENV | grep -q ALIEN_INSTALL_TYPE=system ); then

  echo "system install... pre-install librdkafka-dev"
  cip sudo apt-get update
  cip sudo apt-get -y install librdkafka-dev

else

  echo "share install... pre-install C++, Net::SSLeay and IO::Socket::SSL"
  cip exec cpanm -n Net::SSLeay IO::Socket::SSL
  cip sudo apt-get update
  cip sudo apt-get -y install g++

fi
